name: Build 3DS Homebrew

on:
  push:
    branches: [ 3ds ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --needed --noconfirm 3ds-dev
        sudo dkp-pacman -S --needed --noconfirm libctru citro3d citro2d

    - name: Set up environment
      run: |
        export DEVKITARM=/opt/devkitpro/devkitARM
        export DEVKITPRO=/opt/devkitpro
        echo "DEVKITARM=$DEVKITARM" >> $GITHUB_ENV
        echo "DEVKITPRO=$DEVKITPRO" >> $GITHUB_ENV
        echo "$DEVKITARM/bin" >> $GITHUB_PATH

    - name: Create directory structure
      run: |
        mkdir -p source
        mkdir -p include
        mkdir -p build
        mkdir -p data
        mkdir -p gfx

    - name: Copy source files
      run: |
        # Copy the main source file
        cp main.cpp source/ || echo "No main.cpp found, creating from artifact..."

    - name: Build
      run: |
        make clean
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: google-balls-3ds-homebrew
        path: |
          *.3dsx
          *.smdh
        retention-days: 30

    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.3dsx
          *.smdh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}