name: Build PSP Google Balls

on:
  push:
    branches: [ psp ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ psp ]

jobs:
  build-psp:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    defaults:
      run:
        working-directory: ./psp  # do our stuff in the psp source directory
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install additional dependencies
      run: |
        # Install any additional packages needed (the container uses Alpine Linux)
        apk add --no-cache bash make imagemagick
        
    - name: Build PSP application
      run: |
        # The PSPDEV environment variable is already set in the container
        echo "PSPDEV is set to: $PSPDEV"
        echo "PATH is: $PATH"
        
        # Verify toolchain is available
        which psp-gcc
        psp-gcc --version
        
        # Build the application
        make
        
        # Verify the build was successful
        if [ ! -f "EBOOT.PBP" ]; then
          echo "Build failed - EBOOT.PBP not found"
          exit 1
        fi
        
        # Show build info
        ls -lah EBOOT.PBP
        
    - name: Upload PSP EBOOT
      uses: actions/upload-artifact@v4
      with:
        name: googleballs-psp-${{ github.sha }}
        path: |
          EBOOT.PBP
          *.PBP
          
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          EBOOT.PBP
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}