name: Build PSP Google Balls

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-psp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up PSP toolchain
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git autoconf automake libtool pkg-config
        
        # Create toolchain directory
        mkdir -p $HOME/pspdev
        export PSPDEV=$HOME/pspdev
        export PATH=$PATH:$PSPDEV/bin
        
        # Download and build psptoolchain
        cd $HOME
        git clone https://github.com/pspdev/psptoolchain.git
        cd psptoolchain
        
        # Make the toolchain build script executable
        chmod +x toolchain.sh
        
        # Build the toolchain (this takes a while)
        PSPDEV=$PSPDEV ./toolchain.sh
        
        # Add to PATH permanently for this job
        echo "PSPDEV=$HOME/pspdev" >> $GITHUB_ENV
        echo "$HOME/pspdev/bin" >> $GITHUB_PATH
        
    - name: Install PSP SDL
      run: |
        export PSPDEV=$HOME/pspdev
        export PATH=$PATH:$PSPDEV/bin
        
        # Download and build SDL for PSP
        cd $HOME
        git clone https://github.com/pspdev/SDL.git psp-sdl
        cd psp-sdl
        
        # Configure and build SDL
        make -f Makefile.psp install
        
        # Download and build SDL_image for PSP
        cd $HOME
        git clone https://github.com/pspdev/SDL_image.git psp-sdl-image
        cd psp-sdl-image
        make -f Makefile.psp install
        
    - name: Create PSP icons (if they don't exist)
      run: |
        # Create a simple ICON0.PNG if it doesn't exist
        if [ ! -f "ICON0.PNG" ]; then
          # Use ImageMagick to create a simple icon
          sudo apt-get install -y imagemagick
          convert -size 144x80 xc:blue -fill white -gravity center -pointsize 12 -annotate 0 "Google\nBalls" ICON0.PNG
        fi
        
        # Create a simple PIC1.PNG if it doesn't exist
        if [ ! -f "PIC1.PNG" ]; then
          convert -size 480x272 xc:lightblue -fill darkblue -gravity center -pointsize 24 -annotate 0 "Google Balls PSP" PIC1.PNG
        fi
        
    - name: Build PSP application
      run: |
        export PSPDEV=$HOME/pspdev
        export PATH=$PATH:$PSPDEV/bin
        
        # Make build script executable
        chmod +x build.sh
        
        # Build the application using our build script
        ./build.sh make
        
        # Verify the build was successful
        if [ ! -f "EBOOT.PBP" ]; then
          echo "Build failed - EBOOT.PBP not found"
          exit 1
        fi
        
        # Show build info
        ls -la EBOOT.PBP
        file EBOOT.PBP
        
    - name: Upload PSP EBOOT
      uses: actions/upload-artifact@v4
      with:
        name: googleballs-psp
        path: |
          EBOOT.PBP
          *.PBP