name: Build Tizen Google Balls App

on:
  push:
    branches:
      - tizen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Tizen Studio installer
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/tizen-studio_*.bin
          key: tizen-studio-installer

      - name: Download and Install Tizen Studio
        run: |
          # Download Tizen Studio Web CLI
          wget -q -O web-cli_Tizen_Studio_4.6_ubuntu-64.bin https://download.tizen.org/sdk/Installer/tizen-studio_4.6/web-cli_Tizen_Studio_4.6_ubuntu-64.bin
          chmod +x web-cli_Tizen_Studio_4.6_ubuntu-64.bin
          
          # Install Tizen Studio (headless installation)
          ./web-cli_Tizen_Studio_4.6_ubuntu-64.bin --accept-license --no-java-check
          
          # Add to PATH
          echo "$HOME/tizen-studio/tools/ide/bin" >> $GITHUB_PATH

      - name: Build Tizen Web App
        run: |
          cd tizen
          # Build the web application
          $HOME/tizen-studio/tools/ide/bin/tizen build-web
          
      - name: Create unsigned WGT package
        run: |
          cd tizen/.buildResult
          # Create WGT package manually (it's just a ZIP with .wgt extension)
          zip -r ../googleballs-app-unsigned.wgt *
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tizen-web-app-unsigned
          path: tizen/*.wgt